//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionStartPage.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionStartPage.Core.Localization.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string AddGroup_ToolTip {
            get {
                return ResourceManager.GetString("AddGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk add solutions....
        /// </summary>
        internal static string BulkAddSolutions_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk add solutions (multiple groups).
        /// </summary>
        internal static string BulkAddSolutionsMultipleGroups {
            get {
                return ResourceManager.GetString("BulkAddSolutionsMultipleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds all solutions found below a root directory to a group for their parent directory..
        /// </summary>
        internal static string BulkAddSolutionsMultipleGroups_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutionsMultipleGroups_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk add solutions (single group).
        /// </summary>
        internal static string BulkAddSolutionsSingleGroup {
            get {
                return ResourceManager.GetString("BulkAddSolutionsSingleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds all solutions found below a root directory to a single group..
        /// </summary>
        internal static string BulkAddSolutionsSingleGroup_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutionsSingleGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close page after project load.
        /// </summary>
        internal static string ClosePageAfterProjectLoad {
            get {
                return ResourceManager.GetString("ClosePageAfterProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns:.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Team Foundation Server.
        /// </summary>
        internal static string ConnectToTFS {
            get {
                return ResourceManager.GetString("ConnectToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable editing.
        /// </summary>
        internal static string ContextCommand_EnableEditing {
            get {
                return ResourceManager.GetString("ContextCommand_EnableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Groups.
        /// </summary>
        internal static string DeleteAllGroups_ToolTip {
            get {
                return ResourceManager.GetString("DeleteAllGroups_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory doesn&apos;t exist..
        /// </summary>
        internal static string DirectoryDoesntExist_ToolTip {
            get {
                return ResourceManager.GetString("DirectoryDoesntExist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Preview:.
        /// </summary>
        internal static string DirectoryPreview {
            get {
                return ResourceManager.GetString("DirectoryPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Solution.
        /// </summary>
        internal static string HeaderCommand_AddSolution_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_AddSolution_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Back.
        /// </summary>
        internal static string HeaderCommand_MoveBack_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveBack_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string HeaderCommand_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Forward.
        /// </summary>
        internal static string HeaderCommand_MoveForward_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveForward_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string HeaderCommand_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        internal static string HeaderCommand_RemoveGroup_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_RemoveGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Solution.
        /// </summary>
        internal static string HeaderCommand_RemoveSolution_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_RemoveSolution_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep page open after project loads.
        /// </summary>
        internal static string KeepPageOpenAfterLoad {
            get {
                return ResourceManager.GetString("KeepPageOpenAfterLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project....
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from Source Control....
        /// </summary>
        internal static string OpenFromSourceControl {
            get {
                return ResourceManager.GetString("OpenFromSourceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project....
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the display name..
        /// </summary>
        internal static string SetDisplayName_ToolTip {
            get {
                return ResourceManager.GetString("SetDisplayName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a relative path to the solution file, or an absolute path to any directory..
        /// </summary>
        internal static string SetSolutionDirectoryPath_ToolTip {
            get {
                return ResourceManager.GetString("SetSolutionDirectoryPath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page on startup.
        /// </summary>
        internal static string ShowPageOnStartup {
            get {
                return ResourceManager.GetString("ShowPageOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution file doesn&apos;t exist..
        /// </summary>
        internal static string SolutionDoesntExist_ToolTip {
            get {
                return ResourceManager.GetString("SolutionDoesntExist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
