//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionStartPage.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionStartPage.Core.Localization.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Group ähnelt.
        /// </summary>
        internal static string AddGroup_ToolTip {
            get {
                return ResourceManager.GetString("AddGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bulk add solutions... ähnelt.
        /// </summary>
        internal static string BulkAddSolutions_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bulk add solutions (multiple groups) ähnelt.
        /// </summary>
        internal static string BulkAddSolutionsMultipleGroups {
            get {
                return ResourceManager.GetString("BulkAddSolutionsMultipleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adds all solutions found below a root directory to a group for their parent directory. ähnelt.
        /// </summary>
        internal static string BulkAddSolutionsMultipleGroups_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutionsMultipleGroups_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bulk add solutions (single group) ähnelt.
        /// </summary>
        internal static string BulkAddSolutionsSingleGroup {
            get {
                return ResourceManager.GetString("BulkAddSolutionsSingleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adds all solutions found below a root directory to a single group. ähnelt.
        /// </summary>
        internal static string BulkAddSolutionsSingleGroup_ToolTip {
            get {
                return ResourceManager.GetString("BulkAddSolutionsSingleGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close page after project load ähnelt.
        /// </summary>
        internal static string ClosePageAfterProjectLoad {
            get {
                return ResourceManager.GetString("ClosePageAfterProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Columns: ähnelt.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect To Team Foundation Server ähnelt.
        /// </summary>
        internal static string ConnectToTFS {
            get {
                return ResourceManager.GetString("ConnectToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable editing ähnelt.
        /// </summary>
        internal static string ContextCommand_EnableEditing {
            get {
                return ResourceManager.GetString("ContextCommand_EnableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete All Groups ähnelt.
        /// </summary>
        internal static string DeleteAllGroups_ToolTip {
            get {
                return ResourceManager.GetString("DeleteAllGroups_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The directory doesn&apos;t exist. ähnelt.
        /// </summary>
        internal static string DirectoryDoesntExist_ToolTip {
            get {
                return ResourceManager.GetString("DirectoryDoesntExist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory Preview: ähnelt.
        /// </summary>
        internal static string DirectoryPreview {
            get {
                return ResourceManager.GetString("DirectoryPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display folders ähnelt.
        /// </summary>
        internal static string DisplayFolders {
            get {
                return ResourceManager.GetString("DisplayFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Solution ähnelt.
        /// </summary>
        internal static string HeaderCommand_AddSolution_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_AddSolution_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Back ähnelt.
        /// </summary>
        internal static string HeaderCommand_MoveBack_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveBack_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        internal static string HeaderCommand_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Forward ähnelt.
        /// </summary>
        internal static string HeaderCommand_MoveForward_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveForward_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        internal static string HeaderCommand_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Group ähnelt.
        /// </summary>
        internal static string HeaderCommand_RemoveGroup_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_RemoveGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Solution ähnelt.
        /// </summary>
        internal static string HeaderCommand_RemoveSolution_ToolTip {
            get {
                return ResourceManager.GetString("HeaderCommand_RemoveSolution_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep page open after project loads ähnelt.
        /// </summary>
        internal static string KeepPageOpenAfterLoad {
            get {
                return ResourceManager.GetString("KeepPageOpenAfterLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout ähnelt.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project... ähnelt.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open from Source Control... ähnelt.
        /// </summary>
        internal static string OpenFromSourceControl {
            get {
                return ResourceManager.GetString("OpenFromSourceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Project... ähnelt.
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent ähnelt.
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Projects ähnelt.
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the display name. ähnelt.
        /// </summary>
        internal static string SetDisplayName_ToolTip {
            get {
                return ResourceManager.GetString("SetDisplayName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set a relative path to the solution file, or an absolute path to any directory. ähnelt.
        /// </summary>
        internal static string SetSolutionDirectoryPath_ToolTip {
            get {
                return ResourceManager.GetString("SetSolutionDirectoryPath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page on startup ähnelt.
        /// </summary>
        internal static string ShowPageOnStartup {
            get {
                return ResourceManager.GetString("ShowPageOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The solution file doesn&apos;t exist. ähnelt.
        /// </summary>
        internal static string SolutionDoesntExist_ToolTip {
            get {
                return ResourceManager.GetString("SolutionDoesntExist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
